# Generated by Django 3.1.4 on 2021-01-07 17:17

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_text', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(default=None, verbose_name='date published')),
                ('user_status', models.IntegerField(default=1)),
                ('password', models.CharField(default='12345', max_length=40)),
            ],
        ),
    ]
