# Generated by Django 3.1.4 on 2021-01-07 17:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('datac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 7, 17, 24, 36, 495134, tzinfo=utc), verbose_name='date published'),
        ),
    ]
